### ISSUE TITLE
Depth as png

### ISSUE THREAD

**Issue by dfrumkin** [sniklaus/3d-ken-burns#26]
Hello Simon!
Following https://github.com/sniklaus/3d-ken-burns/issues/11 👍 

- Disparity is resolution-dependent
- Baseline is fixed (resolution independent)

https://github.com/sniklaus/3d-ken-burns/blob/bde67588ff2b0247068fc2fe4419619d47e3a228/depthestim.py#L77

Then their ratio is also resolution-dependent and we may theoretically have problems with clipping, right?

**Comment by sniklaus** [comment]
The clipping definitely does not truthfully preserve the estimate in cases where the disparity magnitude exceeds the clipping threshold. If you would like to use the estimated depth for other tasks, I would recommend storing the depth estimate as a Numpy file instead of an image. You might find the following link useful: https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.tofile.html
