### ISSUE TITLE
Implementation for forward warping

### ISSUE THREAD

**Issue by ShrisudhanG** [sniklaus/3d-ken-burns#58]
Hi @sniklaus, I am working on light fields and am trying to forward warp a monocular image using disparity maps. Can you please help me out in figuring out which python files of this repository should I go through to get a good understanding of the forwards warping and filling occlusion implementation?

Thanks a lot in advance.

**Comment by sniklaus** [comment]
If you just want to do forward warping then this is your best choice since it is also fully differentiable: https://sniklaus.com/softsplat

The implementation for the point cloud rendering is referenced below, but it is quite convoluted and not necessarily easy to read.

https://github.com/sniklaus/3d-ken-burns/blob/726b768467a5726dca75cc155618bd5810eb6ea8/common.py#L345-L710
